#!/usr/bin/env ruby
# encoding: utf-8
# Generated by Walrus <http://walrus.wincent.com/>

begin
  require 'rubygems'
rescue LoadError
  # installing Walrus via RubyGems is recommended
  # otherwise Walrus must be installed in the RUBYLIB load path
end

require 'walrus/document'
require File.expand_path('../../../buildtools/help/master_full_index', File.dirname(__FILE__))

module Walrus
  class Grammar
    class FullIndex < MasterFullIndex
      def template_body
        super # (invoked automatically due to Extends directive)
        # Comment: Copyright 2007-2010 Wincent Colaiuta. All rights reserved.
        # Comment:
        # Comment: Redistribution and use in source and binary forms, with or without
        # Comment: modification, are permitted provided that the following conditions are met:
        # Comment:
        # Comment: 1. Redistributions of source code must retain the above copyright notice,
        # Comment:    this list of conditions and the following disclaimer.
        # Comment: 2. Redistributions in binary form must reproduce the above copyright notice,
        # Comment:    this list of conditions and the following disclaimer in the documentation
        # Comment:    and/or other materials provided with the distribution.
        # Comment:
        # Comment: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        # Comment: AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        # Comment: IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
        # Comment: ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
        # Comment: LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
        # Comment: CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
        # Comment: SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
        # Comment: INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
        # Comment: CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
        # Comment: ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
        # Comment: POSSIBILITY OF SUCH DAMAGE.
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
      end

      def setup
        accumulate('  ') # RawText
        # Include (start): ../settings.txt:
                # Comment: settings.tmpl
                # Comment: A template for application-wide default settings
                # Comment: buildtools help templates
                # Comment:
                # Comment: Copyright 2006-2010 Wincent Colaiuta. All rights reserved.
                # Comment:
                # Comment: Redistribution and use in source and binary forms, with or without
                # Comment: modification, are permitted provided that the following conditions are met:
                # Comment:
                # Comment: 1. Redistributions of source code must retain the above copyright notice,
                # Comment:    this list of conditions and the following disclaimer.
                # Comment: 2. Redistributions in binary form must reproduce the above copyright notice,
                # Comment:    this list of conditions and the following disclaimer in the documentation
                # Comment:    and/or other materials provided with the distribution.
                # Comment:
                # Comment: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
                # Comment: AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
                # Comment: IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
                # Comment: ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
                # Comment: LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
                # Comment: CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
                # Comment: SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
                # Comment: INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
                # Comment: CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
                # Comment: ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
                # Comment: POSSIBILITY OF SUCH DAMAGE.
                accumulate('' + "\n") # RawText
                # Comment:
                # Comment: appliction-wide default settings go in here
                # Comment:
                accumulate('' + "\n") # RawText
                set_value("book_id", instance_eval { 'Hextrapolate Help' }) # Set directive
                set_value("book_icon", instance_eval { 'Hextrapolate Help/gfx/icon16.png' }) # Set directive
                set_value("author", instance_eval { 'Wincent Colaiuta' }) # Set directive
                set_value("author_email", instance_eval { 'win@wincent.com' }) # Set directive
                set_value("copyright", instance_eval { 'Copyright 2007-2010 Wincent Coliauta' }) # Set directive
                accumulate('' + "\n") # RawText
                # Comment:
                # Comment: the page_title should be overridden on a per-page basis
                # Comment:
                accumulate('' + "\n") # RawText
                set_value("page_title", instance_eval { 'Help' }) # Set directive
        accumulate('  ') # RawText
        super # Super directive
      end
      
      def main_box
        accumulate('  ') # RawText
        # Comment: Index items will appear in the order that they are added.
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment: As an alternative to editing this file by hand, there are two helper
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment: scripts that can be run from inside the application help directory:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:    ../../buildtools/help/index_grep.rb:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          Greps through the help directory looking for suitable
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          directives and emits a list of "index_item" links to standard
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          out. To be detected the directives should be of the form:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:                #set $page_title = 'Super title'
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:                #set $tag        = 'super_title'
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          and will yield "index_item" links like:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:                $index_item($link_to('super_title', 'Super title'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:    ../../buildtools/help/update_full_index.rb:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          Takes the output of the index_grep.rb script and inserts it into
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          the file at page/full_index.tmpl inside the application help
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          directory, replacing any existing text between the start and end
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment:          markers
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('  ') # RawText (continued)
        # Comment: -- index items start -- ##
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'ascii', 'ASCII text encoding'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'activation', 'Activation'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'activation_best_practices', 'Activation best practices'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'activation_privacy', 'Activation privacy'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'backing_up_your_license', 'Backing up your license'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'bases', 'Bases'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'before_unregistering', 'Before unregistering'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'binary_representation', 'Binary representation'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'decimal_representation', 'Decimal representation'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'digit_error', 'Digit errors'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'boms', 'Does Hextrapolate use BOMs?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'downloading', 'Downloading Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'locating_hextrapolate', 'Finding out where Hextrapolate is installed'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'force_quitting', 'Force Quitting Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'hexadecimal_representation', 'Hexadecimal representation'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'how_does_activation_work', 'How does product activation work?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'how_many_times_may_i_activate', 'How many times may I activate?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'how_to_file_a_good_bug_report', 'How to file a good bug report'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'feature_requests', 'How to submit a feature request'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'installing', 'Installing Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'learn_about', 'Learn about Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'obtaining_a_system_profiler_report', 'Obtaining a System Profiler report'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'octal_representation', 'Octal representation'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'purchasing', 'Purchasing Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'quitting', 'Quitting Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'registering', 'Registering Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'reporting_bugs', 'Reporting bugs'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'requesting_support', 'Requesting support'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'resetting_the_preferences', 'Resetting the preferences'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'resetting_your_activation_limit', 'Resetting your activation limit'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'sending_feedback', 'Sending feedback'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'super_title', 'Super title'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'encoding_error', 'Text encoding errors'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'text_encodings', 'Text encodings'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'transferring_license', 'Transferring your license to another machine'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'troubleshooting_tips', 'Troubleshooting tips'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'utf16', 'UTF-16 text encoding'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'utf8', 'UTF-8 text encoding'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'uninstalling', 'Uninstalling Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'unregister', 'Unregistering Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'upgrading_hextrapolate', 'Upgrading Hextrapolate'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'what_happens_if_wincent_stops_trading', 'What happens if Wincent stops trading?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'what_happens_if_the_network_is_down', 'What happens if the network is down when I try to activate?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'missing_license', "What to do if you haven't received your license"))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'lost_license_codes', 'What to do if you lose your license code'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'whats_new', "What's new in Hextrapolate?"))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'blank_fields', 'Why are the text fields blank?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'garbage_in_text_fields', 'Why are there garbage characters in the text fields?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'let_me_type', "Why doesn't Hextrapolate let me type the characters I want?"))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:index_item, lookup_and_return_placeholder(:link_to, 'why_use_product_activation', 'Why use product activation?'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        # Comment: -- index items end -- ##
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('  ') # RawText (continued)
        super # Super directive
      end
      
      if __FILE__ == $0   # if run from the command line
        new.run           # same as "walrus run __FILE__"
      else                # if loaded and evaled
        new.fill          # return filled content
      end
    end # FullIndex
  end # Grammar
end # Walrus
