#!/usr/bin/env ruby
# encoding: utf-8
# Generated by Walrus <http://walrus.wincent.com/>

begin
  require 'rubygems'
rescue LoadError
  # installing Walrus via RubyGems is recommended
  # otherwise Walrus must be installed in the RUBYLIB load path
end

require 'walrus/document'
require File.expand_path('../../../buildtools/help/basic', File.dirname(__FILE__))

module Walrus
  class Grammar
    class HowToFileAGoodBugReport < Basic
      def template_body
        super # (invoked automatically due to Extends directive)
        # Comment: Created by Wincent Colaiuta on 11 April 2007.
        # Comment: Copyright 2007 Wincent Colaiuta
        # Comment: $Id: /mirrors/Hextrapolate/trunk/en.lproj/help/example_basic.tmpl.txt 6745 2007-04-12T13:07:56.741665Z wincent  $
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
        # Comment:#############################################################################
        accumulate('' + "\n") # RawText
      end

      def setup
        accumulate('  ') # RawText
        # Include (start): ../settings.txt:
                # Comment: settings.tmpl
                # Comment: A template for application-wide default settings
                # Comment: buildtools help templates
                # Comment:
                # Comment: Copyright 2006-2010 Wincent Colaiuta. All rights reserved.
                # Comment:
                # Comment: Redistribution and use in source and binary forms, with or without
                # Comment: modification, are permitted provided that the following conditions are met:
                # Comment:
                # Comment: 1. Redistributions of source code must retain the above copyright notice,
                # Comment:    this list of conditions and the following disclaimer.
                # Comment: 2. Redistributions in binary form must reproduce the above copyright notice,
                # Comment:    this list of conditions and the following disclaimer in the documentation
                # Comment:    and/or other materials provided with the distribution.
                # Comment:
                # Comment: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
                # Comment: AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
                # Comment: IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
                # Comment: ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
                # Comment: LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
                # Comment: CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
                # Comment: SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
                # Comment: INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
                # Comment: CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
                # Comment: ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
                # Comment: POSSIBILITY OF SUCH DAMAGE.
                accumulate('' + "\n") # RawText
                # Comment:
                # Comment: appliction-wide default settings go in here
                # Comment:
                accumulate('' + "\n") # RawText
                set_value("book_id", instance_eval { 'Hextrapolate Help' }) # Set directive
                set_value("book_icon", instance_eval { 'Hextrapolate Help/gfx/icon16.png' }) # Set directive
                set_value("author", instance_eval { 'Wincent Colaiuta' }) # Set directive
                set_value("author_email", instance_eval { 'win@wincent.com' }) # Set directive
                set_value("copyright", instance_eval { 'Copyright 2007-2010 Wincent Coliauta' }) # Set directive
                accumulate('' + "\n") # RawText
                # Comment:
                # Comment: the page_title should be overridden on a per-page basis
                # Comment:
                accumulate('' + "\n") # RawText
                set_value("page_title", instance_eval { 'Help' }) # Set directive
        accumulate('  ') # RawText
        set_value("page_title", instance_eval { 'How to file a good bug report' }) # Set directive
        accumulate('  ') # RawText
        set_value("tag", instance_eval { 'how_to_file_a_good_bug_report' }) # Set directive
        accumulate('  ') # RawText
        lookup_and_accumulate_placeholder(:see_also, lookup_and_return_placeholder(:link_to, 'troubleshooting_tips'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:see_also, lookup_and_return_placeholder(:link_to, 'reporting_bugs'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:see_also, lookup_and_return_placeholder(:link_to_category, 'troubleshooting'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:category, 'troubleshooting')
        accumulate('' + "\n") # RawText
      end
      
      def content
        accumulate('' + "\n") # RawText
        accumulate('Submitting good bug reports is the best way to get flaws in Hextrapolate fixed as quickly as possible. There are a number of steps you can take to ensure that your bug reports are of high quality:' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('<div id="task_box">' + "\n") # RawText (continued)
        accumulate('  ' + "\n") # RawText (continued)
        accumulate('h2. Perform basic troubleshooting first' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('It\'s important to eliminate possible causes outside of the software. You may find that the problem is being caused by something external to the program, such as a corrupt preferences file, and once you correct the external cause the problem goes away.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('See "') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'troubleshooting_tips')
        accumulate('" for information on basic troubleshooting.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Search before reporting' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Perform a search of the database at <a href="http://bugs.wincent.com/">bugs.wincent.com</a> prior to submitting a report; you can save yourself the effort of filing a report if someone else has already reported the issue.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Find out how to reproduce the bug' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Reproducibility is *the* most important attribute a bug report can have. This means figuring out how to "reproduce" the problem; that is, working out a list of steps required to trigger or cause the bug. Without these instructions I may not be able to fix the bug.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Describe your system' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Include basic information about your system such as:' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('* the version of Mac OS X that you are running' + "\n") # RawText (continued)
        accumulate('* the version of Hextrapolate in which you\'ve found a bug' + "\n") # RawText (continued)
        accumulate('* whether your machine is Intel or PowerPC-based' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('One way of providing all this information and more is by ') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'obtaining_a_system_profiler_report', 'including a system profiler report')
        accumulate('.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Collect information from the Console' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Use the Console application (located in the <tt>Utilities</tt> folder inside the <tt>Applications</tt> folder) to see if anything related to the issue is printed to the <tt>system.log</tt> or <tt>console.log</tt> files. Look for lines which include the word "Hextrapolate", especially lines which contain error messages or warnings.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Save any relevant lines and include them in your report.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Collect information from the Activity Monitor' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('If Hextrapolate stops responding for long periods of time you can use the Activity monitor (located in the <tt>Utilities</tt> folder inside the <tt>Applications</tt> folder) to gather information about where it might be stuck.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Select Hextrapolate from the list of running processes and choose "Sample Process" from the "View" menu, then include the resulting sample in your report.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. One issue per bug report' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Keep your bug report focussed on a single issue. This will make it easier for others to find your bug report in the database and contribute data to help track down the issue.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('</div>' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('To actually report a bug, see ') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'reporting_bugs')
        accumulate('.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
      end
      
      if __FILE__ == $0   # if run from the command line
        new.run           # same as "walrus run __FILE__"
      else                # if loaded and evaled
        new.fill          # return filled content
      end
    end # HowToFileAGoodBugReport
  end # Grammar
end # Walrus
