#!/usr/bin/env ruby
# Generated by Walrus <http://walrus.wincent.com/>

begin
  require 'rubygems'
rescue LoadError
  # installing Walrus via RubyGems is recommended
  # otherwise Walrus must be installed in the RUBYLIB load path
end

require 'walrus/document'
require File.join(File.dirname(__FILE__), '../../../buildtools/help', 'basic').to_s

module Walrus
  class Grammar
    class TroubleshootingTips < Basic
      def template_body
        super # (invoked automatically due to Extends directive)
        # Comment: Created by Wincent Colaiuta on 11 April 2007.
        # Comment: Copyright 2007 Wincent Colaiuta
        # Comment: $Id: /mirrors/Hextrapolate/trunk/en.lproj/help/example_basic.tmpl.txt 6745 2007-04-12T13:07:56.741665Z wincent  $
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
        # Comment:#############################################################################
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)

      end

      def setup
        accumulate('  ') # RawText
        # Include (start): ../settings.txt:
                # Comment: settings.tmpl
                # Comment: A template for application-wide default settings
                # Comment: buildtools help templates
                # Comment:
                # Comment: Copyright 2006-2010 Wincent Colaiuta. All rights reserved.
                # Comment:
                # Comment: Redistribution and use in source and binary forms, with or without
                # Comment: modification, are permitted provided that the following conditions are met:
                # Comment:
                # Comment: 1. Redistributions of source code must retain the above copyright notice,
                # Comment:    this list of conditions and the following disclaimer.
                # Comment: 2. Redistributions in binary form must reproduce the above copyright notice,
                # Comment:    this list of conditions and the following disclaimer in the documentation
                # Comment:    and/or other materials provided with the distribution.
                # Comment:
                # Comment: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
                # Comment: AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
                # Comment: IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
                # Comment: ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
                # Comment: LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
                # Comment: CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
                # Comment: SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
                # Comment: INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
                # Comment: CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
                # Comment: ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
                # Comment: POSSIBILITY OF SUCH DAMAGE.
                accumulate('' + "\n") # RawText
                # Comment:
                # Comment: appliction-wide default settings go in here
                # Comment:
                accumulate('' + "\n") # RawText
                set_value("book_id", instance_eval { 'Hextrapolate Help' }) # Set directive 
                set_value("book_icon", instance_eval { 'Hextrapolate Help/gfx/icon16.png' }) # Set directive 
                accumulate('' + "\n") # RawText
                # Comment:
                # Comment: the page_title should be overridden on a per-page basis
                # Comment:
                accumulate('' + "\n") # RawText
                set_value("page_title", instance_eval { 'Help' }) # Set directive 
        accumulate('  ') # RawText
        set_value("page_title", instance_eval { 'Troubleshooting tips' }) # Set directive 
        accumulate('  ') # RawText
        set_value("tag", instance_eval { 'troubleshooting_tips' }) # Set directive 
        accumulate('  ') # RawText
        lookup_and_accumulate_placeholder(:see_also, lookup_and_return_placeholder(:link_to, 'reporting_bugs'))
        accumulate('' + "\n") # RawText
        accumulate('  ') # RawText (continued)
        lookup_and_accumulate_placeholder(:category, 'troubleshooting')
        accumulate('' + "\n") # RawText
      end
      
      def content
        accumulate('' + "\n") # RawText
        accumulate('There are number of basic troubleshooting techniques that you can try whenever you experience problems with Mac OS X. These tips apply equally to all Mac OS X applications, not just Hextrapolate.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('<div id="task_box">' + "\n") # RawText (continued)
        accumulate('  ' + "\n") # RawText (continued)
        accumulate('h2. Update to the latest version' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('The latest version of Hextrapolate may already contain a fix for the problem. See ') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'upgrading_hextrapolate')
        accumulate(' for information on how to updgrade to the latest version.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Try logging out' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('If you have been logged in for a long time your system\'s environment may have degraded to the point where subtle problems occur. You can rule out these causes by logging out and logging in again. If the problem continues to occur after a log-out/log-in cycle then you should continue troubleshooting.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Try rebooting' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Likewise, if you system has been running for a long time without a reboot performance may be degraded and other subtle problems may occur. Try rebooting and see if the problem persists.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Try an uninstall/reinstall cycle' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Sometimes in the day-to-day use of a system files get moved, deleted, and overwritten. You should try uninstalling the software and then reinstalling it. See ') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'uninstalling')
        accumulate(' and ') # RawText
        lookup_and_accumulate_placeholder(:link_to, 'uninstalling', 'uninstalling Hextrapolate')
        accumulate(' for information on how to do this.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('If the problem goes away, you know that your previous installation was somehow damaged.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Reset your preferences' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Preference files can become corrupted or unreadable over time, and in some cases this can lead to crashes or application misbehaviour. You can rule out this cause by ') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'resetting_the_preferences')
        accumulate('.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Rule out potential conflicts with third-party software' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('If you have any third-party software installed, especially if it is a system modification, it could potentially cause a conflict with other programs on your Mac. To rule out this as a possible cause, try temporarily disabling third-party add-ons and see if the problem goes away.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Check for a corrupt disk' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Check your hard disk for corruption by booting from your Mac OS X install disc and running Disk Utility.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('You can do this by inserting your Mac OS X install disc and restarting while holding down the C key. Once booting is complete you can choose Disk Utility from the Utilities menu and verify your disk.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Try from another user account' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Try to reproduce the problem when logged in to a different user account on the same machine. This will rule out any causes that may be confined to your specific account (settings, caches files, preferences and so on).' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('h2. Try from another machine' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('Taking this troubleshooting technique even further, if you have more than one machine you can try reproducing the problem on another computer. If the problem is present only on one machine then there is possible a local, machine-specific cause.' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('</div>' + "\n") # RawText (continued)
        accumulate('' + "\n") # RawText (continued)
        accumulate('If your troubleshooting is not successful, please ') # RawText (continued)
        lookup_and_accumulate_placeholder(:link_to, 'reporting_bugs', 'file a bug report')
        accumulate(' or ') # RawText
        lookup_and_accumulate_placeholder(:link_to, 'getting_support', 'ask for support')
        accumulate('.' + "\n") # RawText
        accumulate('' + "\n") # RawText (continued)
      end
      

      if __FILE__ == $0   # if run from the command line
        new.run           # same as "walrus run __FILE__"
      end
    end # TroubleshootingTips
  end # Grammar
end # Walrus
